### ISSUE TITLE
An open & close button for each door.

### ISSUE THREAD

**Issue by DervMan** [andrewshilliday/garage-door-controller#47]
My garage door opener requires a separate button for open & close. Any chance we can provide the option for this type of door? Can't seem to DM you, let me have your email and I'll send you the details for accessing my door opener.

**Comment by andrewshilliday** [comment]
Can you send a link to the controller?  That might be a bit complicated of an update.  One alternative could be to get a (single button) wireless garage door opener and wire that into the raspberry pi instead of going directly to the opener.

**Comment by DervMan** [comment]
Annoyingly my door remote has two buttons too, so although it's a good idea it wouldn't work!

**Comment by danblade** [comment]
Andrew has written his code very well. 

I was able to copy and past the lines of code in the config.jason file.

` "left" :
                       {
                       "name" : "CLOSE",
                       "relay_pin" : 23,
                       "state_pin" : 27,
                       "approx_time_to_close" : 15,
                       "approx_time_to_open" : 15
                       },
`

Simply paste it below and change the name "left" to "middle" and change the pin numbers to an unused set. I utilized this excellent code for a commercial door opener which requires stop, open, and close. It works perfectly! (I did go with the sainsmart_4_channel_relay instead of the 2 channel relay.)

![garage door buttons](https://cloud.githubusercontent.com/assets/18683963/22978193/5be4f924-f357-11e6-8d96-327214f91131.jpg)

The stop utilizes a break in power so you use the other side of the relay... (if you get into it, you will understand...).

![sainsmart_4_channel_relay](https://cloud.githubusercontent.com/assets/18683963/22978229/810510ea-f357-11e6-87c3-cf64305bbdaa.jpg)



Andrew, Thank you for writing this!

**Comment by andrewshilliday** [comment]
My pleasure!   I'm glad it's working out for you!

**Comment by zackoch** [comment]
You could just treat each button like a separate door yeah?

**Comment by danblade** [comment]
Exactly what I did.

**Comment by andrewshilliday** [comment]
So you're all good then?  OK to close out this issue?

**Comment by DervMan** [comment]
I'm making do with a second door icon. It works but I get duplicate emails. Not had time to play. Go ahead and close the ticket as it works for me.
